<?php
/**
 * @var $block \Buzzi\PublishPageView\Block\EventTrigger
 */
?>

<div class="buzzi-page-view-container" data-role="buzzi-page-view" data-bind="scope: 'buzzi-page-view'">
</div>

<script type="text/x-magento-init">
    {
        "[data-role=buzzi-page-view]": {
            "Buzzi_PublishPageView/js/event-trigger": {
                "event_type": "<?= $block->escapeJsQuote($block->getEventType(), "\"") ?>",
                "page_id": "<?= $block->escapeJsQuote($block->getPageId(), "\"") ?>",
                "site_id": "<?= $block->escapeJsQuote($block->getWebsiteCode(), "\"") ?>",
                "category": "<?= $block->escapeJsQuote($block->getCurrentCategoryName(), "\"") ?>"
            }
        }
    }
</script>
